version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: nodemon ./index.js
    volumes:
      - ./index.js:/usr/src/app/index.js
    ports:
      - "3000:3000"