version: '3.4'

services:  

  app-web:
    container_name: app-web
    build:
      context: ./app-web/
      dockerfile: Dockerfile
    networks:
       - overlay
    ports:
      - target: 80        # port in contaner
        published: 80     # port in local
        protocol: tcp     #
        mode: ingress     #
    volumes:         
      - ./app-web/:/usr/src/app/
    stdin_open: true
    tty: true  

  api-login:
    container_name: api-login
    build:
      context: ./api-login/
      dockerfile: Dockerfile
    networks:
       - overlay
    ports:
      - target: 8080      # port in contaner
        published: 81     # port in local
        protocol: tcp     #
        mode: ingress     #
    volumes:         
      - ./api-login/:/usr/src/app/
    stdin_open: true
    tty: true  
  
  # Database management in a single PHP file
  # https://www.adminer.org/
  # adminer:
  #   image: adminer:latest
  #   container_name: adminer
  #   networks:
  #      - overlay
  #   restart: always
  #   ports:
  #     - 8080:8080
  
networks:
  overlay: